name: Generate Release Notes

on:
  schedule:
    # Run every Friday at 3:00 PM UTC
    - cron: '0 15 * * 5'
  workflow_dispatch:
    inputs:
      since_days:
        description: 'Number of days to look back'
        required: true
        default: '7'
      version:
        description: 'Version number for the release'
        required: false

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    # Alternatively: runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate release notes
        run: |
          python -m src.main \
            --config config/config.json \
            --since-days ${{ github.event.inputs.since_days || '7' }} \
            ${{ github.event.inputs.version && format('--version {0}', github.event.inputs.version) || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
      
      - name: Upload release notes
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: output/